// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";
import type { Db, MongoClient } from "npm:mongodb";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import ViewerConcept from "./Viewer/ViewerConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import AuthorizationConcept from "./Authorization/AuthorizationConcept.ts";
import RolesConcept from "./Roles/RolesConcept.ts";
import ReservationConcept from "./Reservation/ReservationConcept.ts";

export type { default as ViewerConcept } from "./Viewer/ViewerConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as AuthorizationConcept } from "./Authorization/AuthorizationConcept.ts";
export type { default as RolesConcept } from "./Roles/RolesConcept.ts";
export type { default as ReservationConcept } from "./Reservation/ReservationConcept.ts";

// Initialize the database connection
export const [db, client] = (await getDb()) as [Db, MongoClient];

export const Viewer = Engine.instrumentConcept(new ViewerConcept());
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
// Pass the Mongo Db to AuthorizationConcept while relaxing types for compatibility
export const Authorization = Engine.instrumentConcept(
  new AuthorizationConcept(db as unknown as never),
);
export const Roles = Engine.instrumentConcept(new RolesConcept(db));
export const Reservation = Engine.instrumentConcept(new ReservationConcept(db));
